# NextMe Windows 计划任务安装脚本
#
# 用途：将 NextMe 注册为 Windows 计划任务，使其在用户登录后自动启动，
#       并将输出重定向到日志文件。
#
# 用法（以管理员身份运行 PowerShell）：
#   .\windows-service-install.ps1            # 安装并立即启动
#   .\windows-service-install.ps1 -Uninstall # 停止并卸载
#
# 要求：Windows 10/11，已安装 uv，已完成 nextme 配置（%USERPROFILE%\.nextme\settings.json）

param(
    [switch]$Uninstall
)

$ErrorActionPreference = "Stop"

$TaskName   = "NextMe Bot"
$LogDir     = "$env:USERPROFILE\.nextme\logs"
$LogFile    = "$LogDir\nextme.log"
$ProjectDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$Settings   = "$env:USERPROFILE\.nextme\settings.json"
$WrapperScript = "$ProjectDir\nextme-wrapper.ps1"

function Write-Ok   { param($msg) Write-Host "✓  $msg" -ForegroundColor Green }
function Write-Warn { param($msg) Write-Host "⚠  $msg" -ForegroundColor Yellow }
function Write-Err  { param($msg) Write-Host "✗  $msg" -ForegroundColor Red }

# ---------------------------------------------------------------------------
# 卸载
# ---------------------------------------------------------------------------
if ($Uninstall) {
    Write-Host ""
    Write-Host "╔══════════════════════════════╗" -ForegroundColor Blue
    Write-Host "║   NextMe 计划任务卸载        ║" -ForegroundColor Blue
    Write-Host "╚══════════════════════════════╝" -ForegroundColor Blue
    Write-Host ""

    $task = Get-ScheduledTask -TaskName $TaskName -ErrorAction SilentlyContinue
    if ($task) {
        Stop-ScheduledTask  -TaskName $TaskName -ErrorAction SilentlyContinue
        Unregister-ScheduledTask -TaskName $TaskName -Confirm:$false
        Write-Ok "计划任务 '$TaskName' 已停止并删除"
    } else {
        Write-Warn "未找到计划任务 '$TaskName'，跳过删除"
    }

    if (Test-Path $WrapperScript) {
        Remove-Item $WrapperScript -Force
        Write-Ok "已删除包装脚本：$WrapperScript"
    }

    Write-Host ""
    Write-Ok "卸载完成。如需重新安装，再次运行 .\windows-service-install.ps1"
    exit 0
}

# ---------------------------------------------------------------------------
# 安装
# ---------------------------------------------------------------------------
Write-Host ""
Write-Host "╔══════════════════════════════════╗" -ForegroundColor Blue
Write-Host "║   NextMe 计划任务安装            ║" -ForegroundColor Blue
Write-Host "╚══════════════════════════════════╝" -ForegroundColor Blue
Write-Host ""

# 检查 uv
$uvPath = (Get-Command uv -ErrorAction SilentlyContinue)?.Source
if (-not $uvPath) {
    Write-Err "未找到 uv，请先安装："
    Write-Err "   powershell -ExecutionPolicy ByPass -c `"irm https://astral.sh/uv/install.ps1 | iex`""
    exit 1
}
Write-Ok "uv：$uvPath"

# 检查配置文件
if (-not (Test-Path $Settings)) {
    Write-Err "未找到 %USERPROFILE%\.nextme\settings.json"
    $example = "$ProjectDir\settings.json.example"
    if (Test-Path $example) {
        Write-Err "请先执行：New-Item -ItemType Directory -Force `$env:USERPROFILE\.nextme; Copy-Item '$example' '$Settings'"
    }
    exit 1
}
Write-Ok "配置文件：$Settings"

# 创建日志目录
New-Item -ItemType Directory -Force -Path $LogDir | Out-Null
Write-Ok "日志目录：$LogDir"

# 生成包装脚本（计划任务调用此脚本，将 stdout/stderr 追加写入日志）
@"
# Auto-generated by windows-service-install.ps1 — do not edit
`$LogFile = '$LogFile'
`$ProjectDir = '$ProjectDir'
`$uvPath = '$uvPath'

& `$uvPath run --project `$ProjectDir nextme up *>> `$LogFile
"@ | Set-Content -Path $WrapperScript -Encoding UTF8
Write-Ok "已写入包装脚本：$WrapperScript"

# 删除旧任务（如存在）
$existing = Get-ScheduledTask -TaskName $TaskName -ErrorAction SilentlyContinue
if ($existing) {
    Write-Warn "发现已有计划任务，正在重新注册..."
    Stop-ScheduledTask  -TaskName $TaskName -ErrorAction SilentlyContinue
    Unregister-ScheduledTask -TaskName $TaskName -Confirm:$false
}

# 注册计划任务
$action  = New-ScheduledTaskAction `
    -Execute "powershell.exe" `
    -Argument "-NonInteractive -WindowStyle Hidden -ExecutionPolicy Bypass -File `"$WrapperScript`""

$trigger = New-ScheduledTaskTrigger -AtLogOn -User "$env:USERDOMAIN\$env:USERNAME"

$settings = New-ScheduledTaskSettingsSet `
    -ExecutionTimeLimit (New-TimeSpan -Hours 0) `
    -RestartCount 99 `
    -RestartInterval (New-TimeSpan -Seconds 30) `
    -MultipleInstances IgnoreNew `
    -StartWhenAvailable

$principal = New-ScheduledTaskPrincipal `
    -UserId "$env:USERDOMAIN\$env:USERNAME" `
    -LogonType Interactive `
    -RunLevel Limited

Register-ScheduledTask `
    -TaskName $TaskName `
    -Action $action `
    -Trigger $trigger `
    -Settings $settings `
    -Principal $principal `
    -Description "NextMe Feishu Bot — auto-restart on crash" | Out-Null

Write-Ok "计划任务 '$TaskName' 已注册"

# 立即启动
Start-ScheduledTask -TaskName $TaskName
Write-Ok "服务已启动"

Write-Host ""
Write-Host "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━" -ForegroundColor Green
Write-Host "  安装完成！NextMe 现已作为后台任务运行。" -ForegroundColor Green
Write-Host "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━" -ForegroundColor Green
Write-Host ""
Write-Host "  日志：  Get-Content '$LogFile' -Wait -Tail 50"
Write-Host "  状态：  Get-ScheduledTask -TaskName '$TaskName'"
Write-Host "  停止：  Stop-ScheduledTask -TaskName '$TaskName'"
Write-Host "  启动：  Start-ScheduledTask -TaskName '$TaskName'"
Write-Host "  卸载：  .\windows-service-install.ps1 -Uninstall"
Write-Host ""
